apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: laboulette
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: laboulette
          servicePort: 80
