# Use postgres/example user/password credentials
version: '3.1'
services:
  db:
    image: postgres
    restart: always
    networks:
      - reverse_proxy
    volumes:
      - database-data:/var/lib/postgresql/data/
    env_file: .env
    ports:
      - 5432:5432
  calendso:
    build: .
    restart: always
    env_file: .env
    ports:
      - 5555:5555
      - 3000:3000
    networks:
      - reverse_proxy
    depends_on:
      - db
    labels:
      - traefik.enable=true
      - traefik.http.routers.cal.rule=Host(`cal.${DOMAIN_NAME}`)
      - traefik.http.routers.cal.tls.certresolver=leresolver
      - traefik.http.routers.cal.entrypoints=websecure
      - traefik.http.services.cal.loadbalancer.server.port=3000
volumes:
  database-data:

networks:
  reverse_proxy:
    external: true
