version: "3.7"

services:
  valheim: 
    image: ${IMAGE_NAME}
    cap_add:
      - sys_nice
    volumes: 
      - $HOME/valheim-server/config:/config
      - $HOME/valheim-server/data:/opt/valheim
    ports: 
      - "9001:9001/tcp"
    stop_grace_period: 2m
    restart: always
    networks:
      - reverse_proxy
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      - ${STORAGE_LOCATION}/valheim:/dist
    labels:
      - traefik.enable=true
      - traefik.http.routers.valheim.rule=Host(`valheim.${DOMAIN_NAME}`)
      - traefik.http.routers.valheim.tls.certresolver=leresolver
      - traefik.http.routers.valheim.entrypoints=websecure
      - traefik.http.services.valheim.loadbalancer.server.port=${PORT}

networks:
  reverse_proxy:
    external: true
