version: "3.7"

services:
  app:
    image: yoangau/laboulette-server
    restart: always
    networks:
      - reverse_proxy
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${STORAGE_LOCATION}/laboulette:/dist
    labels:
      - traefik.enable=true
      - traefik.http.routers.calibre.rule=Host(`laboulette.${DOMAIN_NAME}`)
      - traefik.http.routers.calibre.tls.certresolver=leresolver
      - traefik.http.routers.calibre.entrypoints=websecure

networks:
  reverse_proxy:
    external: true
